# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-03 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181003_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='height_field',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='width_field',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field'),
        ),
    ]
