# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-03 11:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181003_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 10, 3, 11, 51, 37, 909215, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
